### ISSUE TITLE
How to remove transitive dependencies? (copy from clue/graph)

### ISSUE THREAD

**Issue by clemens-tolboom** [clue/graph-uml#10]
This is a copy from https://github.com/clue/graph/issues/85

In my class diagrams I have unnecessary links cluttering the display

See in this one having (in the upper left corner) links to Traversable both from Child class and it's parent.

![drush-uml](https://f.cloud.github.com/assets/371014/1645512/3196e544-5902-11e3-9a60-a430778d7508.png)  

How can I remove these? Use an algorithm?

**Comment by clue** [comment]
Turns out this is an issue with the way `ReflectionClass::getInterfaces()` works. It does not only return the interfaces the given class implements, but also any inherited interfaces.

``` php
interface A { }
interface B extends A { }
class C implements B { }
```

``` php
$reflection = new ReflectionClass('C');
var_dump($reflection->getInterfaces());
```

This will return A and B whereas one might expect just B. We can probably work around this by checking its parent classes for interfaces and skipping those already present.

The thing is, there's apparently no way to distinguish the following case:

``` php
interface A { }
interface B extends A { }
class C implements A, B { }
```

So in both cases we'd end up with the same graph.

That situation isn't perfect either, but it sounds like a fair compromise in my opinion.

**Comment by clemens-tolboom** [comment]
The Reflection examples above are clear to me. Reflection delivers.

I'd like to have an option to reduce the edges as a visualization aid. (Less paper, better learning curves)

So my guess is this should be done by graph :)

Should we reopen https://github.com/clue/graph/issues/85 ?

**Comment by clue** [comment]
Consider the following example (from your attached graph image):

``` php
interface DrushCacheInterface { }
class DrushFileCache implements DrushCacheInterface { }
class DrushJSONCache extends DrushFileCache { }
```

The `DrushJSONCache` does not _explicitly_ implement the `DrushCacheInterface`, so the graph should not include an edge either. Of course, due to extending the `DrushFileCache` which implements the interface, it implements the interface _implicitly_ and hence why `ReflectionClass::getInterfaces()` also returns a reference to it as well.

See my above description about how we could check the other interfaces and its parent class to eliminate the unneeded edges. This will ultimately lead to the situation that there's no way to check whether it actually also explicitly implements the interface, but IMO that's a rare case and it's probably _okay_ to hide it from the graph in that case.

**Comment by clemens-tolboom** [comment]
Hmmm ... I still think this is a 'common' graph problem removing implicit edges. In `A -> B, B -> C, A -> C` edge `A -> C` can be removed.

For graph-uml we only need an option to apply the 'remove transitives`

Or am I missing the point?!?

**Comment by clue** [comment]
> I still think this is a 'common' graph problem

You're right :) We should probably add a feature request for a new algorithm that calculates the [transitive reduction](http://en.wikipedia.org/wiki/Transitive_reduction) of a given DAG. So yeah, feel free to re-open the ticket (or create a new one) as a feature request for clue/graph so we can keep track of the progress.

> For graph-uml we only need an option…

In my opinion this should be the default for clue/graph-uml. As per the above discussion there's little sense in _ever_ having any of the useless edges, as they're merely a result of how `ReflectionClass::getInterfaces()` works. So I'd like to track this as a bug for clue/graph-uml.
